core_index:
    path:     /
    defaults: { _controller: core.page_controller:dashboardAction }

core_dashboard:
    path:     /dashboard
    defaults: { _controller: core.page_controller:dashboardAction }

core_settings:
    path:     /settings
    defaults:
        _controller: core.page_controller:settingsAction

core_projects:
    path:     /projects
    defaults:
        _controller: core.page_controller:projectsAction

core_project:
    path:     /project/{id}
    defaults:
        _controller: core.page_controller:projectAction
    methods: [GET]
    requirements:
        id:  \d+

core_help:
    path:     /help
    defaults:
        _controller: core.page_controller:helpAction

core_dashboard_deployments:
    path:     /dashboard-deployments/{amount}
    defaults:
        _controller: core.page_controller:dashboardDeploymentsAction
        amount: 20
    methods: [GET]
    requirements:
        amount:  \d+
