core_index:
    path:     /
    defaults: { _controller: core.page_controller:dashboardAction }

core_dashboard:
    path:     /dashboard
    defaults: { _controller: core.page_controller:dashboardAction }
