services:
    # twig template functions #################################################
    core.twig.mx_extension:
        class: CoreBundle\Twig\CoreExtension
        arguments:
            - '@core.config'
        tags:
            - { name: twig.extension }

    # configuration loader ####################################################
    core.config:
        class: Core\Config\ConfigManager
        arguments:
            - '@doctrine_cache.providers.default'
            - '%kernel.environment%'
            - '%kernel.root_dir%'

    # parent service for controller-as-a-service ##############################
    core.abstract_service_controller:
        abstract:  true
        arguments:
            - '@templating'
            - '@form.factory'
            - '@doctrine.orm.php_deploy_entity_manager'
            - '@security.token_storage'

    # forms ###################################################################
    core.project_form:
        class: CoreBundle\Form\ProjectType
        tags:
            - { name: form.type, alias: asm_project_form }

    # ansible #################################################################
    core.ansible:
        class: Core\Ansible\Ansible
        arguments:
            - '%ansible_playbook_command%'
            - '%ansible_galaxy_command%'
