#!/usr/bin/env php
<?php
/*
 * This file is part of the php-deploy package.
 *
 * (c) Marc Aschmann <maschmann@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__ . '/../vendor/autoload.php';

use Asm\PhpDeploy\Console\Command\DeployCommand;
use Symfony\Component\Console\Application;

set_time_limit(0);

$application = new Application();
$application->add(new DeployCommand);
$application->run();
