---
- hosts: localhost
  remote_user: root
  roles:
    - servergrove.symfony2

  vars:
    symfony2_project_root: /tmp/test_app
    symfony2_project_name: deployment-test
    symfony2_project_composer_path: /tmp/test_app/shared
    symfony2_project_repo: https://github.com/symfony/symfony-standard.git
    symfony2_project_branch: "2.7"
    symfony2_project_php_path: php
    symfony2_project_env: prod
    symfony2_project_console_opts: '--no-debug'
    symfony2_project_composer_opts: '--no-dev --optimize-autoloader'
    symfony2_project_keep_releases: 5
    symfony2_project_clean_versioning: true
